### ISSUE TITLE
Training script for HPatches dataset

### ISSUE THREAD

**Issue by xmlyqing00** [TencentYoutuResearch/AdaMatcher#4]
Hi,

Thanks for releasing the code to public, I have a question that how do you train your model for HPatches? Did it train on HPatches or it was trained on MegaDepth then evaluated on HPatches.

Thanks,
Yongqing

**Comment by AbyssGaze** [comment]
我已经收到您的邮件哦！
祝您开心每一天！

**Comment by AbyssGaze** [comment]
All of the evaluations utilize the same model, which is trained on the
Megadepth dataset.

Yongqing Liang ***@***.***> 于2023年8月31日周四 00:45写道：

**Comment by xmlyqing00** [comment]
Thanks for your explanation
